name: Trigger workflow update on change of terminology
on:
  repository_dispatch:
    types: terminology_updated
jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger workflow update on change of terminology
        uses: frdrwrt/write-to-file@v1.3
        with:
          # The filename you want to store as csv
          filepath: terminology.csv
          content: ${{ github.event.client_payload.terminology }}
      - name: Commit terminology
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'deriv-pocs@users.noreply.github.com'
          git add terminology.csv
          git commit -am "Custom Terminology Updated"
          git push
      - name: Use aws cli to import termonology
        run: |
          aws translate delete-terminology \
          --name DerivCustomTerminology \
          --description "Deriv Custom Terminology Dictionary" \
          --merge-strategy OVERWRITE \
          --data-file fileb://terminology.csv \
          --terminology-data Format=CSV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'